In [3]:
import pandas as pd
import numpy as np

In [4]:
raw = pd.read_csv("../data/raw/nyc311_2025_sample.csv")

In [5]:
raw.head()

,unique_key,created_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,borough,city,latitude,longitude,closed_date
0,63577994,2025-01-01T00:00:12.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10466.0,BRONX,BRONX,40.891872,-73.860168,2025-01-02T17:05:54.000
1,63584096,2025-01-01T00:00:13.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,11211.0,BROOKLYN,BROOKLYN,40.711210,-73.958973,2025-01-01T00:05:19.000
2,63581480,2025-01-01T00:00:17.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10466.0,BRONX,BRONX,40.891872,-73.860168,2025-01-01T09:01:06.000
3,63575612,2025-01-01T00:00:19.000,NYPD,New York City Police Department,Illegal Fireworks,NaN,Street/Sidewalk,11230.0,BROOKLYN,BROOKLYN,40.629240,-73.968790,2025-01-01T00:43:08.000
4,63586536,2025-01-01T00:00:34.000,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,APARTMENT ONLY,RESIDENTIAL BUILDING,10466.0,BRONX,BRONX,40.891940,-73.852775,2025-01-02T12:04:30.000

In [6]:
raw.shape

(100000, 13)

In [7]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   unique_key      100000 non-null  int64
 1   created_date    100000 non-null  object
 2   agency          100000 non-null  object
 3   agency_name     100000 non-null  object
 4   complaint_type  100000 non-null  object
 5   descriptor      98782 non-null   object
 6   location_type   92031 non-null   object
 7   incident_zip    99527 non-null   float64
 8   borough         100000 non-null  object
 9   city            97700 non-null   object
 10  latitude        99206 non-null   float64
 11  longitude       99206 non-null   float64
 12  closed_date     100000 non-null  object
dtypes: float64(3), int64(1), object(9)
memory usage: 9.9+ MB

In [8]:
raw.describe()

         unique_key  incident_zip      latitude     longitude
count  1.000000e+05  99527.000000  99206.000000  99206.000000
mean   6.363687e+07  10720.423342     40.779239    -73.906001
std    3.514626e+04    482.960463      0.099871      0.067994
min    6.357209e+07   7307.000000     40.500889    -74.253178
25%    6.361069e+07  10458.000000     40.692051    -73.950324
50%    6.363674e+07  10466.000000     40.797731    -73.897531
75%    6.366275e+07  11221.000000     40.891872    -73.860168
max    6.907434e+07  11694.000000     40.911829    -73.701665

In [9]:
raw.isnull().sum()

unique_key           0
created_date         0
agency               0
agency_name          0
complaint_type       0
descriptor        1218
location_type     7969
incident_zip       473
borough              0
city              2300
latitude           794
longitude          794
closed_date          0
dtype: int64

In [12]:
raw.duplicated().sum()

np.int64(0)

In [9]:
created = pd.to_datetime(raw["created_date"])
closed = pd.to_datetime(raw["closed_date"])

resolution_days = (closed - created).dt.total_seconds() / (24 * 60 * 60)

In [10]:
resolution_days.describe()

count    100000.000000
mean          8.386056
std          32.876383
min          -2.243750
25%           0.078238
50%           0.509508
75%           1.990162
max         603.805347
dtype: float64